### PR TITLE
Update 2022 november

### LINKED ISSUE #34: Update registry data for dashboard
👋 @delwen !

Per our decision to update the data for the dashboard, I started a branch: [update-2022-november](https://github.com/maia-sh/intovalue-data/tree/update-2022-november).

I ran scripts 6-10, and pushed the resulting higher-level files (not raw/processed). Now the OA from you, and we can create the updated trials.csv.

Also, we should decide where to store the raw data, both for this and April 2022 updates, and future such updates. Perhaps updating [https://zenodo.org/record/6560383](https://zenodo.org/record/6560383)? Let's discuss.

### PR DESCRIPTION
**Pull request by maia-sh**
Closes #34

### CODE REVIEW

**Comment by maia-sh** [comment]
Since we decided not to update the log files in this branch, and instead do so in main after, I manually set `aact_query_date` and `drks_query_date` to "2022-11-01". As such `registry_download_date` and other resulting columns in `trials` reflect the true registry date.

**Review by delwen — APPROVED** [review]
Looks good! This will be used to update the dashboard data (new query dates: 1 November 2022).

**Comment by maia-sh** [comment]
{"timestamp": "2022-11-01T11:11:08+0100", "log_lvl": "INFO", "log_msg": "AACT"}
{"timestamp": "2022-11-01T11:16:48+0100", "log_lvl": "INFO", "log_msg": "DRKS"}
{"timestamp": "2022-11-02T18:14:02+0100", "log_lvl": "INFO", "log_msg": "AACT_ctgov_2018"}

**Comment by delwen** [comment]
queries.log

{"timestamp": "2022-11-01T11:11:08+0100", "log_lvl": "INFO", "log_msg": "AACT"}
{"timestamp": "2022-11-01T11:16:48+0100", "log_lvl": "INFO", "log_msg": "DRKS"}
{"timestamp": "2022-11-01T17:23:43+0100", "log_lvl": "INFO", "log_msg": "Unpaywall"}
{"timestamp": "2022-11-01T17:29:27+0200", "log_lvl": "INFO", "log_msg": "ShareYourPaper"}
{"timestamp": "2022-11-02T18:14:02+0100", "log_lvl": "INFO", "log_msg": "AACT_ctgov_2018"}

syp-query.log

ShareYourPaper query date: 01-11-2022 05:29:27 PM

**Pull request merged**
